### PR TITLE
Only allow single Refresh at a time

### LINKED ISSUE #315: Refreshing multiple times ends in incorrect place in tree
If I open a subscription and press `F5` then the display is refreshed. If I then press `F5` again then I end up back at the subscription list

### PR DESCRIPTION
**Pull request by stuartleeks**
Fixes #315 

- Prevent multiple concurrent refreshes (since refresh performs a Back and Navigate using the current list state)
- Disable UI updates during a refresh (to mask the Back/Navigate actions)

### CODE REVIEW

File: internal/pkg/views/list.go [hunk 1]
```diff
@@ -219,19 +233,32 @@ func (w *ListWidget) Refresh() {
 	}
 
 	w.GoBack()
-	w.ExpandCurrentSelection()
+	w.expandItem(currentExpandedItem)
 
-	w.ChangeSelection(currentSelection)
+	// wait for navigation before resetting previous selection
+	go func() {
+		navigatedChannel := eventing.SubscribeToTopic("list.navigated")
```
Comment (lawrencegripper) [inline internal/pkg/views/list.go:240]:
```suggestion
		defer errorhandling.RecoveryWithCleanup()
		navigatedChannel := eventing.SubscribeToTopic("list.navigated")
```

In the off chance that this fails adding recovery will ensure the terminal is left in a usable state and stack is printed etc

Comment (lawrencegripper) [reply internal/pkg/views/list.go:240]: Think this'll need an additional import of `"github.com/lawrencegripper/azbrowse/internal/pkg/errorhandling"`

**Review by lawrencegripper — APPROVED** [review]
LGTM
