### PR TITLE
Re-enable "Update current item" command

### LINKED ISSUE #222: Update command to edit resources not working
On latest master, the "Update current item" command is not enabled even on nodes that support editing, and the keyboard shortcut has no effect

### PR DESCRIPTION
**Pull request by stuartleeks**
Leaf node navigation now stores the node on the Content view and the ListUpdate command now checks the Content view node. This allows resource editing to work without reverting to behaviour that allows infinite expansion of a leaf node.

PR also changes `make debug` to use `dlv debug` as this gives a richer debug experience compared to debugging the compiled binary. Happy to pull this into a separate PR if preferred

Fixes #222

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -35,7 +35,7 @@ build: swagger-codegen test checks
 ## debug:
 ##		Starts azbrowse using Delve ready for debugging from VSCode.
 debug:
-	GO111MODULE=on go build ./cmd/azbrowse &&  dlv exec ./azbrowse --headless --listen localhost:2345 --api-version 2
```
Comment (lawrencegripper) [inline Makefile]: Nice!

File: internal/pkg/views/list.go [hunk 2]
```diff
@@ -254,31 +254,30 @@ func (w *ListWidget) Navigate(nodes []*expanders.TreeNode, content *expanders.Ex
...
 	if len(nodes) > 0 {
 		w.expandedNodeItem = currentItem
 		w.SetNodes(nodes)
-	}
 
-	w.contentView.SetContent(content.Response, content.ResponseType, title)
-	if currentItem != nil {
-		w.title = w.title + ">" + currentItem.Name
+		if currentItem != nil {
+			w.title = w.title + "fooo>" + currentItem.Name
```
Comment (lawrencegripper) [inline internal/pkg/views/list.go]:
```suggestion
			w.title = w.title + ">" + currentItem.Name
```

Comment (lawrencegripper) [reply internal/pkg/views/list.go]: image

Nit: guess this was for testing

File: internal/pkg/keybindings/listhandlers.go [hunk 3]
```diff
@@ -496,7 +496,7 @@ func (h *ListUpdateHandler) IsEnabled() bool {
 	return true
 }
 func (h *ListUpdateHandler) Invoke() error {
-	item := h.List.CurrentExpandedItem()
+	item := h.Content.GetNode()
 	if !h.IsEnabled() {
 		return nil
```
Comment (lawrencegripper) [inline internal/pkg/keybindings/listhandlers.go]:
```suggestion
		eventing.SendStatusEvent(&eventing.StatusEvent{
			InProgress: false,
			Failure:    true,
			Message:    "Updating not supported on this item",
			Timeout:    time.Duration(time.Second * 2),
		})
		return nil
```

File: internal/pkg/views/list.go (hunk 2 above)
Comment (lawrencegripper) [reply internal/pkg/views/list.go]: Fixed

File: internal/pkg/keybindings/listhandlers.go (hunk 3 above)
Comment (lawrencegripper) [reply internal/pkg/keybindings/listhandlers.go]: Added

**Comment by lawrencegripper** [comment]
Found the issue with the fuzzer, all nodeIds were coming through as root so causing the state to get confused. All fixed up now, will merge once build is passed.

**Comment by stuartleeks** [comment]
Thanks for the fixes :-)
